import=["~/.config/alacritty/themes/themes/tokyo_night.yaml"]

[window]
opacity=0.9

[font]
normal={family="MesloLGM Nerd Font", style="Regular"}
italic={family="MesloLGM Nerd Font", style="Italic"}
bold={family="MesloLGM Nerd Font", style="Bold"}
size=10.5
