local dap = require("dap")

vim.keymap.set("n", "<leader>dc", dap.continue, { desc = 'DAP continue' })
vim.keymap.set("n", "<leader>dq", dap.close, { desc = 'DAP quit' })
vim.keymap.set('n', '<F10>', dap.step_over, { desc = 'DAP step over' })
vim.keymap.set('n', '<F11>', dap.step_into, { desc = 'DAP step in' })
vim.keymap.set('n', '<F12>', dap.step_out, { desc = 'DAP step out' })
vim.keymap.set('n', '<leader>b', dap.toggle_breakpoint, { desc = 'DAP toggle breakpoint' })
vim.keymap.set('n', '<leader>B', dap.set_breakpoint, { desc = 'DAP set breakpoint' })
vim.keymap.set('n', '<leader>lp', function() dap.set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end, { desc = 'DAP set log point message' })
vim.keymap.set('n', '<leader>dro', dap.repl.open, { desc = 'DAP REPL open' })
vim.keymap.set('n', '<leader>drq', dap.repl.close, { desc = 'DAP REPL close' })
vim.keymap.set('n', '<leader>dl', dap.run_last, { desc = 'DAP run last' })
vim.keymap.set({'n', 'v'}, '<leader>dh', function()
  require('dap.ui.widgets').hover()
end, { desc = 'DAP UI hover' })
vim.keymap.set({'n', 'v'}, '<leader>dp', function()
  require('dap.ui.widgets').preview()
end, { desc = 'DAP UI preview' })
vim.keymap.set('n', '<leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end, { desc = 'DAP UI frames' })
vim.keymap.set('n', '<leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end, { desc = 'DAP UI scopes' })

require('dap-python').setup('~/dev/bin/python')
